apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    jenkins.io/github-folder: nimak-org/backstage-test
    spinnaker.io/application: lambda
    code.aws.com/region: us-west-2
    build.code.aws.com/project: hello-world
    deploy.code.aws.com/application: hello-world
    pipeline.code.aws.com/name: test-pipeline
  name: nk-artist-lookup
  description: Artist Lookup
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: experimental
  owner: team-b
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
